import * as FileSystem from 'expo-file-system';

export async function exportScanReport({ moduleName, result, imageUri, severity }) {
  const ts = new Date().toISOString();
  const safeModule = moduleName.replace(/\s+/g, '_').toLowerCase();
  const filename = `${safeModule}_report_${Date.now()}.txt`;
  const fileUri = `${FileSystem.documentDirectory}${filename}`;

  const report = [
    'TomatoDoc - AI Scan Report',
    '=========================',
    `Generated At: ${ts}`,
    `Module: ${moduleName}`,
    '',
    `Class: ${result.class}`,
    `Confidence: ${result.confidence}%`,
    `Severity Score: ${severity.score}/100 (${severity.level})`,
    `Description: ${result.description || '-'}`,
    `Symptoms: ${result.symptoms || '-'}`,
    `Recommendation: ${result.solution || '-'}`,
    `Treatment/Fertilizer: ${result.treatment || result.fertilizer || '-'}`,
    `Warning: ${result.warning || '-'}`,
    `Image URI: ${imageUri || '-'}`,
    '',
    'Generated by TomatoDoc mobile app.',
  ].join('\n');

  await FileSystem.writeAsStringAsync(fileUri, report, {
    encoding: FileSystem.EncodingType.UTF8,
  });

  return fileUri;
}

